FROM node:16 AS node_builder

WORKDIR /app
ENV NODE_ENV=development

COPY *.json ./
COPY ./res ./res
COPY ./src ./src

RUN npm install && \
    npm run build && \
    npm prune --omit=dev && \
    npm cache clean --force

FROM ruby:3.2
LABEL org.opencontainers.image.authors="Christoph Fabianek <christoph@ownyourdata.eu>"

COPY docker/local-gem/*.gem /tmp/

RUN groupadd -r user && \
    useradd -r -g user -m -d /home/user -s /bin/bash user && \
    mkdir -p /tmp/apt-cache && \
    apt-get update && \
    apt-get -o Dir::Cache::archives=/tmp/apt-cache install -y --no-install-recommends \
        libsodium-dev \
        jq \
        python3-pip && \
    gem install /tmp/*.gem && \
    gem install httparty ed25519 multibases multihashes multicodecs json-canonicalization optparse rbnacl dag uri && \
    gem install securerandom -v 0.1.1 && \
    ln -sf /usr/bin/python3 /usr/bin/python && \
    python3 -m pip install --no-cache-dir pytest requests pytest-subprocess --break-system-packages && \
    wget https://raw.githubusercontent.com/OwnYourData/oydid/main/cli/oydid.rb -O /usr/local/bin/oydid && \
    chmod 755 /usr/local/bin/oydid && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/apt-cache /tmp/*.gem /root/.cache /tmp/*

COPY --from=node_builder /usr/local /usr/local

WORKDIR /usr/src/app

COPY --chown=user:user --from=node_builder /app/dist /usr/src/app/dist
COPY --chown=user:user --from=node_builder /app/res /usr/src/app/res
COPY --chown=user:user --from=node_builder /app/*.json /usr/src/app/
COPY --chown=user:user --from=node_builder /app/node_modules /usr/src/app/node_modules

COPY ./docker/start.sh /usr/local/bin/start.sh
COPY --chown=user:user ./docker ./docker

RUN npm run bin && \
    chown -R user:user /usr/src/app && \
    sed -e "s/\${soya}/$(soya --version)/" -e "s/\${jq}/$(jq --version)/" docker/welcome.txt > /etc/motd

USER user
WORKDIR /home/user
CMD ["/usr/local/bin/start.sh"]