apiVersion: apps/v1
kind: Deployment
metadata:
  name: soya
spec:
  replicas: 2
  selector:
    matchLabels:
      app: soya
  template:
    metadata:
      labels:
        app: soya
    spec:
      containers:
      - name: soya
        image: oydeu/soya-base:latest
        ports:
        - containerPort: 3000
        env:
          - name: LANG
            value: C.UTF-8
          - name: RAILS_LOG_TO_STDOUT
            value: "TRUE"
          - name: RAILS_ENV
            value: production
          - name: SEMCON_DB
            value: kubernetes
          - name: DB_HOST
            value: pg_pod_name.default.svc.cluster.local
          - name: DB_NAME
            value: soya
          - name: DB_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: general-secrets
                key: db-passwd
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: soya-secrets
                key: secret-key-base