source 'https://rubygems.org'

ruby '3.1.3'

gem 'rails'
gem 'sqlite3'
gem 'pg'
gem 'puma'
gem 'doorkeeper'
gem 'rack-cors', require: 'rack/cors'
gem 'jbuilder'
gem 'rbnacl'
gem 'httparty'
gem 'merkle-hash-tree'
gem 'responders'
gem 'sprockets'
gem 'rswag'
gem 'linkeddata'
gem 'rdf'
gem 'rdf-trig'
gem 'delayed_job_active_record'
gem 'paypal-sdk-rest'
gem 'pagy', '~> 3.5'
gem 'hashlink'
gem 'ed25519'
gem 'base58'
gem 'dag'
gem 'json-canonicalization'
gem 'mimemagic', github: 'mimemagicrb/mimemagic', ref: '01f92d86d15d85cfd0f20dabd025dcbd36a8a60f'
gem 'string-similarity'
gem 'json-ld' 
gem 'multibases'
gem 'multihashes'
gem 'uri'

# update for security fixes
gem 'loofah'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails'
end

group :development do
  # gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'better_errors'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'annotate'
  gem 'rails-erd'
  gem 'derailed_benchmarks'
end
