meta:
  name: Person
  namespace:
    foaf: "http://xmlns.com/foaf/0.1/"

content:
  bases: 
    - name: Person
      subClassOf: foaf:Person
      attributes:
        name: String
        dateOfBirth: Date
        age: Integer
        sex: String
