meta:
  name: PersonStack
  namespace:
    foaf: "http://xmlns.com/foaf/0.1/"
    dc: "http://purl.org/dc/elements/1.1/"

content:
  base: 
    - name: Person
      attributes:
        name: String
        dateOfBirth: Date
        age: Integer
        sex: String

  overlays: 
    - type: OverlayAnnotation
      base: Person
      name: PersonAnnotationOverlay
      class: 
        label: 
          en: Person
          de: 
            - die Person
            - der Mensch
      attributes:
        name: 
          label: 
            en: Name
            de: Name
        dateOfBirth:
          label: 
            en: Date of Birth 
            de: Geburtsdatum
          comment: 
            en: Birthdate of Person
        sex: 
          label: 
            en: Gender
            de: Geschlecht
          comment: 
            en: Gender (male or female)
            de: Geschlecht (männlich oder weiblich)

    - type: OverlayClassification
      base: Person
      name: PersonClassificationOverlay
      attributes:
        name: pii
        dateOfBirth: pii
        sex: 
          - pii
          - gdpr_sensitive

    - type: OverlayEncoding
      base: Person
      name: PersonEncodingOverlay
      attributes:
        name: UTF-8
        dateOfBirth: UTF-8
        age: UTF-8
        sex: UTF-8

    - type: OverlayFormat
      base: Person
      name: PersonFormatOverlay
      attributes:
        dateOfBirth: DD/MM/YYYY

    - type: OverlayAlignment
      base: Person
      name: PersonAlignmentOverlay
      attributes:
        name: 
          - foaf:name
          - dc:title
        sex: foaf:gender

    - type: OverlayValidation
      base: Person
      name: PersonValidationOverlay
      attributes:
        name: 
          cardinality: "1..1"
          length: "[0..20)"
          pattern: "^[a-z ,.'-]+$"
        dateOfBirth:
          cardinality: "1..1"
          valueRange: "[1900-01-01..*]"
        age: 
          cardinality: "0..1"
          valueRange: "[0..*]"
        sex:
          cardinality: "0..1"
          valueOption:
            - male
            - female
