apiVersion: apps/v1
kind: Deployment
metadata:
  name: soya-beta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soya-beta
  template:
    metadata:
      name: soya-beta
      labels:
        app: soya-beta
    spec:
      containers:
      - name: soya-beta
        image: oydeu/soya-repo:latest
        env:
          - name: CONTAINER_NAME
            value: "SOyA Repository"
          - name: LANG
            value: C.UTF-8
          - name: RAILS_LOG_TO_STDOUT
            value: "TRUE"
          - name: LOG_LEVEL
            value: "INFO"
          - name: RAILS_SERVE_STATIC_FILES
            value: "TRUE"
          - name: RAILS_ENV
            value: production
          - name: DC_DB
            value: kubernetes
          - name: DB2_HOST
            value: postgres
          - name: DB2_NAME
            value: soya-repo
          - name: DB2_USER
            value: postgres
          - name: POSTGRES2_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: superUserPassword
---
kind: Service
apiVersion: v1
metadata:
  name: soya-beta
spec:
  selector:
    app: soya-beta
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: soya-beta
  annotations:
    certmanager.io/issuer: "letsencrypt-prod"
spec:
  ingressClassName: "nginx"
  tls:
  - hosts:
    - soya-beta.ownyourdata.eu
    secretName: soya-beta-tls
  rules:
  - host: soya-beta.ownyourdata.eu
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: soya-beta
            port:
              number: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: soya-beta-tls
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  secretName: soya-beta-tls
  issuerRef:
    group: cert-manager.io
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - 'soya-beta.ownyourdata.eu'
